

apiVersion: v1
kind: Service
metadata:
  name: news-flash-service
spec:
  selector:
    app: flash-app-service
  ports:
    - protocol: "TCP"
      port: 5000
      targetPort: 5000
  type: LoadBalancer


---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: flash-app
spec:
  selector:
    matchLabels:
      app: flash-app-service
  replicas: 2
  template:
    metadata:
      labels:
        app: flash-app-service
    spec:
      containers:
        - name: flash-app-service
          image: docker.io/semha/ex-arbete:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: NEWS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-key-secret
                  key: NEWS_API_KEY


---


apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: news-flash
  namespace: argocd
spec:
  description: News Flash Project
  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
  sourceRepos:
    - https://github.com/11haile/news-flash-doe21.git


---


apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/newsflash"
        backend:
          service:
            name: news-flash-service
            port:
              number: 5000
      - pathType: Prefix
        path: "/argocd"
        backend:
          service:
            name: argocd-service
            port:
              number: 5000


---